# Generated by Django 4.1.6 on 2023-04-04 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_useraccount_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='Sexe',
            field=models.CharField(default='Homme', max_length=255),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='Sexe',
            field=models.CharField(default='Homme', max_length=255),
        ),
    ]
