# Generated by Django 4.1.6 on 2023-04-11 23:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_expert_sexe_useraccount_sexe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='Sexe',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='Sexe',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('im', models.FileField(null=True, upload_to='public')),
                ('vd', models.FileField(null=True, upload_to='public')),
                ('nb', models.IntegerField(default=0)),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.useraccount')),
            ],
        ),
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('description', models.TextField()),
                ('im', models.FileField(null=True, upload_to='public')),
                ('b', models.BooleanField(default=False)),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
