# Generated by Django 4.1.6 on 2023-04-17 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_expertcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='nb',
        ),
        migrations.AddField(
            model_name='post',
            name='bc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='bv',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PostVerifie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('im', models.FileField(blank=True, null=True, upload_to='public')),
                ('vd', models.FileField(blank=True, null=True, upload_to='public')),
                ('sentiment', models.IntegerField(default=0)),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.useraccount')),
            ],
        ),
        migrations.CreateModel(
            name='PostSupp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('im', models.FileField(blank=True, null=True, upload_to='public')),
                ('vd', models.FileField(blank=True, null=True, upload_to='public')),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.useraccount')),
            ],
        ),
    ]
