# Generated by Django 4.1.6 on 2023-04-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_comment_idpost_alter_expertcomment_idpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='bc',
        ),
        migrations.AddField(
            model_name='postverifie',
            name='bc',
            field=models.BooleanField(default=False),
        ),
    ]
