# Generated by Django 4.1.6 on 2023-04-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_comment_sentiment_expertcomment_sentiment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='sentiment',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='expertcomment',
            name='sentiment',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
